config/routes.rb
Projectb::Application.routes.draw do
  resources :comments
  resources :posts do

    resources :comments
  end

  get "users/show"

  resources :posts
  resources :approval

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  get 'terms' => 'pages#terms'

  root :to => 'posts#index'

end

app/controllers/approval_controller.rb
class ApprovalController < ApplicationController
  before_filter :authenticate_user!
  before_filter do 
    redirect_to home_path unless user_signed_in? && current_user.admin?
  end

  def index
    @posts = Post.order("created_at desc").page(params[:page]).per_page(50)
  end


  def edit
    @post = Post.find(params[:id])
    # redirect_to approval_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to approval_index_path, notice: 'This post has been updated. Keep up the good work! -Jon' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/views/approval/_approval.html.erb
<!-- This page displays the moderation page. -->

<div class="row">
  <div class="span6 offset3">
    <div class="box">
      <p>
        <%= post.description %>
      </p>
      <p>
        <strong>
          posted by <%= post.user.username unless post.user.nil? %>
        </strong>
      </p>
      <% if post.approved? %>
        <div class="approved">
          <p>
            Approved. <%= link_to 'Dispprove', edit_approval_path(post) %>
          </p>
        </div>
      <% else %>
        <div class="approval">
          <p>
            Needs approval: <%= link_to 'Approve?', edit_approval_path(post) %>
          </p>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/approval/_form.html.erb
<%= simple_form_for(@post, :url => approval_path, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <p>
    <div class="row">
      <div class="span6 offset3">
        <div class="box">
      	   <%= @post.description %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="span3 offset1">
        <p>Edit post (if necessary):</p>
          <%= f.input :description, label: "&nbsp;", input_html: { rows: 8, style: 'width: 350px', maxlength: 4000 } %>
      </div>
    </div>
  </p>
  <p>
  	Check this box and press 'Update Post' to approve. 
  </p>
  <p>
    Uncheck the box and press 'Update Post' to disapprove. The post will not be displayed on the main page.
  </p>

  <b>Approve/Disapprove:</b>	<%= f.check_box :approved, {}, 'true', 'false' %>
  

 

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/approval/edit.html.erb
<h1>Approving Posts</h1>
<%= render 'form' %>

<%= link_to 'Back', approval_index_path %>

app/views/approval/index.html.erb
<div id="box">
	<h1>Welcome Admin. Please approve these posts:</h1>
	<%= render partial: 'approval', collection: @posts, as: :post %>
</div>

<%= will_paginate @posts %>