config/routes.rb
Projectb::Application.routes.draw do
  resources :comments
  resources :posts do

    resources :comments
  end

  get "users/show"

  resources :posts
  resources :approval

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  get 'terms' => 'pages#terms'

  root :to => 'posts#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">

 <ul class="footernav">	
  <small>
    <li>&#169; 2013 &nbsp;&nbsp;<%= link_to "JobConfession", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "FAQ", faq_path %></li>
    <li><%= link_to "Terms", terms_path %></li>
  </small>
 </ul>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">


              <!-- Be sure to leave the brand out there if you want it shown -->
              <%= link_to "JobConfession", root_path, class: "brand" %>
 
              
                <!-- .nav, .navbar-search, .navbar-form, etc -->
                  <ul class="nav">
                   <li><%= link_to "About", about_path, class: "navcolor" %></li>
                   <li><%= link_to "FAQ", faq_path, class: "navcolor" %></li>
                   <% if @admin %>
                    <li><%= link_to "Moderate", approval_index_path, class: "navcolor" %></li>
                    <% end %> 
                  </ul>
          
           <ul class="nav pull-right">   
            <li>
              <div id="user_nav">
                <% if user_signed_in? %>
                <%= link_to new_post_path do %>
                <button class="btn-default btn btn-success">New Post</button>
                <% end %>
                &nbsp;<%= link_to edit_user_registration_path do %>
                <button class="btn-default btn btn-info">Edit Profile</button>
                <% end %>&nbsp;
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger btn-default' %>
                <% else %>
                <%= link_to new_user_registration_path do %>
                <button class="btn-default btn btn-info">Sign Up!</button>
                <% end %>
                &nbsp;<%= link_to new_user_session_path do %>
                <button class="btn btn-success btn-default">Sign In</button>
                <% end %>
                <% end %>
              </div>
            </li> 
          </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
		<head>
		  <title>JobConfession - What are some secrets from your workplace?</title>
		  <%= stylesheet_link_tag    "application", :media => "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <meta content="A place where people share secrets and stories about things that happen in their workplace." name="description" />
			<!-- start Mixpanel -->
			<script type="text/javascript">
			(function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");
			b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+
			'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';d=c.getElementsByTagName("script")[0];
			d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){
			var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(
			Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==typeof f?g=a[f]=[]:
			f="mixpanel";g.people=g.people||[];h=['disable','track','track_pageview','track_links',
			'track_forms','register','register_once','unregister','identify','alias','name_tag','set_config',
			'people.set','people.set_once','people.increment','people.track_charge','people.append'];
			for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.2;})(document,window.mixpanel||[]);
			mixpanel.init("145d7a8ad0d95f015c989d835ace25ec");
			</script>
			<!-- end Mixpanel -->
		</head>
	<body>
	<!-- start Facebook like button -->
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=105040976211886";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	<!-- end Facebook like button -->


  	    <%= render 'layouts/header' %>
  	    	<div class="container">  <!-- May change this to container-fluid -->
  	    		<% flash.each do |name, msg| %>
                	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            	<% end %>
				<%= yield %>
				<%= render 'layouts/footer' %>
			</div>  
	</body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-13130101-5', 'jobconfession.com');
  ga('send', 'pageview');

</script>
	
</html>